-- Iron Miles foods seed (generated from food-database.json)
-- 140 rows

create table if not exists public.foods (
  id text primary key,
  name text not null,
  type text not null check (type in ('meal', 'snack', 'drink')),
  category text not null,
  calories int,
  protein int,
  carbs int,
  fat int,
  tags text[],
  health_score int,
  convenience_score int,
  truck_access_score int,
  created_at timestamptz not null default now(),
  is_active boolean not null default true
);

insert into public.foods (
  id,
  name,
  type,
  category,
  calories,
  protein,
  carbs,
  fat,
  tags,
  health_score,
  convenience_score,
  truck_access_score,
  is_active
) values
  ('fuel_restaurants_001', 'Turkey Breast 6-inch', 'meal', 'restaurants', 280, 18, 46, 4, ARRAY['lean_protein', 'low_fat']::text[], 4, 5, 5, true),
  ('fuel_restaurants_002', 'Veggie Delight 6-inch', 'meal', 'restaurants', 230, 8, 44, 2, ARRAY['low_calorie', 'vegetarian']::text[], 4, 5, 5, true),
  ('fuel_restaurants_003', 'Oven Roasted Chicken 6-inch', 'meal', 'restaurants', 320, 23, 41, 5, ARRAY['lean_protein']::text[], 4, 5, 5, true),
  ('fuel_restaurants_004', 'Black Forest Ham 6-inch', 'meal', 'restaurants', 290, 18, 46, 4, ARRAY['lean_protein']::text[], 3, 5, 5, true),
  ('fuel_restaurants_005', 'Chicken Bowl (no cheese, no sour cream)', 'meal', 'restaurants', 480, 42, 45, 14, ARRAY['high_protein', 'balanced']::text[], 4, 3, 3, true),
  ('fuel_restaurants_006', 'Steak Bowl (light rice)', 'meal', 'restaurants', 520, 39, 40, 20, ARRAY['high_protein']::text[], 3, 3, 3, true),
  ('fuel_restaurants_007', 'Veggie Bowl', 'meal', 'restaurants', 420, 12, 55, 14, ARRAY['vegetarian', 'fiber_rich']::text[], 4, 3, 3, true),
  ('fuel_restaurants_008', 'Chicken Salad Bowl', 'meal', 'restaurants', 360, 38, 12, 18, ARRAY['low_carb', 'high_protein']::text[], 5, 3, 3, true),
  ('fuel_restaurants_009', 'Grilled Chicken Sandwich', 'meal', 'restaurants', 380, 37, 44, 7, ARRAY['lean_protein']::text[], 4, 5, 5, true),
  ('fuel_restaurants_010', 'Side Salad (no dressing)', 'snack', 'restaurants', 20, 2, 4, 0, ARRAY['low_calorie']::text[], 5, 5, 5, true),
  ('fuel_restaurants_011', 'Egg McMuffin', 'meal', 'restaurants', 300, 17, 30, 12, ARRAY['balanced']::text[], 3, 5, 5, true),
  ('fuel_restaurants_012', 'Fruit & Maple Oatmeal', 'meal', 'restaurants', 320, 6, 64, 4, ARRAY['fiber_rich']::text[], 3, 5, 5, true),
  ('fuel_restaurants_013', 'Grilled Chicken Wrap', 'meal', 'restaurants', 300, 20, 26, 13, ARRAY['balanced']::text[], 3, 5, 5, true),
  ('fuel_restaurants_014', 'Chili (Small)', 'meal', 'restaurants', 240, 16, 21, 7, ARRAY['high_protein']::text[], 4, 4, 5, true),
  ('fuel_restaurants_015', 'Apple Bites', 'snack', 'restaurants', 35, 0, 8, 0, ARRAY['low_calorie']::text[], 5, 5, 5, true),
  ('fuel_restaurants_122', 'Southwest Avocado Chicken Salad', 'meal', 'restaurants', 560, 42, 18, 38, ARRAY['high_protein', 'healthy_fats']::text[], 4, 4, 5, true),
  ('fuel_restaurants_016', 'Power Menu Bowl (Chicken)', 'meal', 'restaurants', 480, 26, 49, 20, ARRAY['balanced']::text[], 3, 4, 5, true),
  ('fuel_restaurants_017', 'Soft Taco (Chicken)', 'snack', 'restaurants', 190, 12, 18, 8, ARRAY['lean_protein']::text[], 3, 5, 5, true),
  ('fuel_restaurants_123', 'Chicken Soft Taco (Fresco Style)', 'meal', 'restaurants', 150, 12, 16, 4, ARRAY['lean_protein', 'low_fat']::text[], 4, 5, 5, true),
  ('fuel_restaurants_124', 'Chicken Power Bowl (No Rice)', 'meal', 'restaurants', 330, 26, 12, 20, ARRAY['high_protein', 'low_carb']::text[], 4, 4, 5, true),
  ('fuel_restaurants_018', 'String Bean Chicken Breast', 'meal', 'restaurants', 190, 13, 13, 9, ARRAY['lean_protein']::text[], 4, 4, 3, true),
  ('fuel_restaurants_019', 'Broccoli Beef', 'meal', 'restaurants', 150, 9, 13, 7, ARRAY['balanced']::text[], 4, 4, 3, true),
  ('fuel_restaurants_126', 'Chicken Teriyaki Bowl', 'meal', 'restaurants', 400, 25, 55, 8, ARRAY['balanced']::text[], 3, 4, 3, true),
  ('fuel_restaurants_020', 'Turkey Bacon & Egg White Sandwich', 'meal', 'restaurants', 230, 17, 28, 5, ARRAY['lean_protein']::text[], 4, 5, 3, true),
  ('fuel_restaurants_021', 'Protein Box (Eggs & Cheese)', 'meal', 'restaurants', 470, 23, 40, 23, ARRAY['high_protein']::text[], 3, 5, 3, true),
  ('fuel_restaurants_125', 'Grilled Chicken & Hummus Protein Box', 'meal', 'restaurants', 450, 27, 42, 18, ARRAY['balanced', 'high_protein']::text[], 4, 5, 3, true),
  ('fuel_restaurants_022', 'Mediterranean Bowl (Chicken)', 'meal', 'restaurants', 590, 29, 69, 21, ARRAY['balanced']::text[], 3, 3, 2, true),
  ('fuel_restaurants_023', 'Greek Salad', 'meal', 'restaurants', 400, 7, 17, 35, ARRAY['vegetarian']::text[], 3, 4, 2, true),
  ('fuel_restaurants_127', 'Chicken Noodle Soup', 'meal', 'restaurants', 160, 10, 20, 4, ARRAY['light_meal']::text[], 4, 5, 5, true),
  ('fuel_restaurants_128', 'Avocado Chicken Bowl', 'meal', 'restaurants', 520, 32, 48, 22, ARRAY['balanced', 'healthy_fats']::text[], 4, 3, 2, true),
  ('fuel_restaurants_024', 'Grilled Chicken Breast', 'meal', 'restaurants', 210, 38, 0, 7, ARRAY['high_protein', 'low_carb']::text[], 4, 5, 5, true),
  ('fuel_restaurants_025', 'Green Beans', 'snack', 'restaurants', 25, 1, 4, 0, ARRAY['low_calorie']::text[], 5, 5, 5, true),
  ('fuel_restaurants_129', 'Grilled Chicken Breast (No Bun)', 'meal', 'restaurants', 180, 33, 0, 4, ARRAY['lean_protein', 'low_carb']::text[], 5, 5, 5, true),
  ('fuel_restaurants_130', 'Mashed Potatoes (No Gravy)', 'meal', 'restaurants', 110, 2, 17, 4, ARRAY['light_meal']::text[], 3, 5, 5, true),
  ('fuel_restaurants_026', 'Fit Slam', 'meal', 'restaurants', 450, 24, 60, 12, ARRAY['balanced']::text[], 3, 2, 5, true),
  ('fuel_restaurants_027', 'Grilled Chicken Salad', 'meal', 'restaurants', 320, 28, 18, 14, ARRAY['lean_protein']::text[], 4, 3, 5, true),
  ('fuel_restaurants_131', 'Fit Fare Veggie Skillet', 'meal', 'restaurants', 330, 21, 28, 14, ARRAY['balanced']::text[], 4, 2, 5, true),
  ('fuel_restaurants_132', 'Chicken & Vegetable Skillet', 'meal', 'restaurants', 420, 32, 30, 18, ARRAY['balanced', 'high_protein']::text[], 4, 2, 5, true),
  ('fuel_restaurants_120', 'Grilled Chicken Cool Wrap', 'meal', 'restaurants', 350, 37, 29, 13, ARRAY['lean_protein', 'balanced']::text[], 4, 4, 5, true),
  ('fuel_restaurants_121', 'Grilled Nuggets (8-count)', 'meal', 'restaurants', 130, 25, 1, 3, ARRAY['lean_protein', 'low_carb']::text[], 5, 5, 5, true),
  ('fuel_truckstop_028', 'Hard-Boiled Eggs (2-pack)', 'snack', 'truck_stop_foods', 140, 12, 2, 9, ARRAY['high_protein', 'portable']::text[], 4, 5, 5, true),
  ('fuel_truckstop_029', 'Greek Yogurt Cup', 'snack', 'truck_stop_foods', 120, 12, 14, 0, ARRAY['high_protein', 'cooler_friendly']::text[], 4, 4, 5, true),
  ('fuel_truckstop_030', 'Fresh Fruit Cup', 'snack', 'truck_stop_foods', 90, 1, 22, 0, ARRAY['low_calorie', 'hydrating']::text[], 5, 5, 5, true),
  ('fuel_truckstop_031', 'Turkey & Cheese Snack Pack', 'snack', 'truck_stop_foods', 260, 20, 8, 16, ARRAY['high_protein']::text[], 3, 5, 5, true),
  ('fuel_truckstop_133', 'Chicken Breast (Grilled, Hot Case)', 'meal', 'truck_stop_foods', 210, 36, 2, 6, ARRAY['lean_protein']::text[], 4, 5, 5, true),
  ('fuel_truckstop_032', 'Rotisserie Chicken (Breast Portion)', 'snack', 'truck_stop_foods', 220, 40, 0, 6, ARRAY['high_protein', 'low_carb']::text[], 5, 4, 5, true),
  ('fuel_truckstop_033', 'Steamed Veggies', 'snack', 'truck_stop_foods', 80, 3, 12, 2, ARRAY['fiber_rich']::text[], 5, 4, 5, true),
  ('fuel_truckstop_034', 'Grilled Chicken Breast Plate', 'meal', 'truck_stop_foods', 260, 38, 4, 9, ARRAY['lean_protein']::text[], 4, 3, 5, true),
  ('fuel_truckstop_035', 'Baked Potato (Plain)', 'snack', 'truck_stop_foods', 160, 4, 37, 0, ARRAY['complex_carbs']::text[], 4, 4, 5, true),
  ('fuel_truckstop_134', 'Chicken Veggie Soup Cup', 'meal', 'truck_stop_foods', 140, 10, 18, 3, ARRAY['light_meal']::text[], 4, 5, 5, true),
  ('fuel_truckstop_036', 'Turkey Burger (No Bun)', 'meal', 'truck_stop_foods', 240, 28, 4, 12, ARRAY['low_carb', 'high_protein']::text[], 4, 3, 5, true),
  ('fuel_truckstop_037', 'Garden Salad', 'snack', 'truck_stop_foods', 110, 3, 10, 7, ARRAY['low_calorie']::text[], 5, 4, 5, true),
  ('fuel_truckstop_038', 'Oatmeal Cup', 'snack', 'truck_stop_foods', 150, 5, 27, 3, ARRAY['fiber_rich']::text[], 4, 5, 5, true),
  ('fuel_truckstop_039', 'Protein Snack Box', 'snack', 'truck_stop_foods', 320, 24, 18, 18, ARRAY['high_protein']::text[], 3, 5, 5, true),
  ('fuel_truckstop_040', 'Chicken Caesar Wrap', 'meal', 'truck_stop_foods', 420, 28, 32, 18, ARRAY['balanced']::text[], 3, 5, 5, true),
  ('fuel_truckstop_041', 'Veggie Snack Tray', 'snack', 'truck_stop_foods', 70, 2, 14, 0, ARRAY['low_calorie', 'hydrating']::text[], 5, 5, 5, true),
  ('fuel_truckstop_042', 'Hummus & Pretzels', 'snack', 'truck_stop_foods', 250, 7, 30, 10, ARRAY['vegetarian']::text[], 3, 5, 5, true),
  ('fuel_truckstop_135', 'Chicken Wrap (Grab-and-Go)', 'meal', 'truck_stop_foods', 320, 24, 28, 12, ARRAY['balanced']::text[], 3, 5, 5, true),
  ('fuel_truckstop_043', 'Grilled Chicken Strips', 'snack', 'truck_stop_foods', 210, 32, 4, 7, ARRAY['lean_protein']::text[], 4, 4, 5, true),
  ('fuel_truckstop_044', 'Fruit & Nut Snack Pack', 'snack', 'truck_stop_foods', 280, 6, 32, 14, ARRAY['healthy_fats']::text[], 3, 5, 5, true),
  ('fuel_truckstop_045', 'Chicken Noodle Soup Cup', 'snack', 'truck_stop_foods', 190, 12, 22, 5, ARRAY['comfort_food']::text[], 3, 4, 5, true),
  ('fuel_truckstop_046', 'Egg & Cheese Breakfast Sandwich', 'meal', 'truck_stop_foods', 340, 18, 30, 16, ARRAY['balanced']::text[], 3, 5, 5, true),
  ('fuel_packaged_047', 'Greek Yogurt (Plain, 150g)', 'snack', 'packaged_foods', 120, 12, 8, 0, ARRAY['high_protein']::text[], 5, 4, 5, true),
  ('fuel_packaged_048', 'Protein Bar (Low Sugar)', 'snack', 'packaged_foods', 180, 20, 15, 6, ARRAY['high_protein', 'portable']::text[], 4, 5, 5, true),
  ('fuel_packaged_049', 'Tuna Packets', 'snack', 'packaged_foods', 70, 16, 0, 1, ARRAY['lean_protein']::text[], 5, 5, 5, true),
  ('fuel_packaged_050', 'Mixed Nuts (28g)', 'snack', 'packaged_foods', 170, 6, 6, 15, ARRAY['healthy_fats']::text[], 3, 5, 5, true),
  ('fuel_packaged_051', 'Beef Jerky (Low Sodium)', 'snack', 'packaged_foods', 80, 12, 3, 2, ARRAY['high_protein']::text[], 4, 5, 5, true),
  ('fuel_packaged_052', 'String Cheese', 'snack', 'packaged_foods', 80, 7, 1, 6, ARRAY['portable', 'high_protein']::text[], 4, 5, 5, true),
  ('fuel_packaged_053', 'Cottage Cheese Cup', 'snack', 'packaged_foods', 110, 13, 5, 5, ARRAY['high_protein']::text[], 5, 4, 5, true),
  ('fuel_packaged_054', 'Hummus Cup with Pretzels', 'snack', 'packaged_foods', 250, 7, 30, 10, ARRAY['vegetarian']::text[], 3, 5, 5, true),
  ('fuel_packaged_055', 'Granola Bar (Low Sugar)', 'snack', 'packaged_foods', 140, 4, 22, 4, ARRAY['portable']::text[], 3, 5, 5, true),
  ('fuel_packaged_056', 'Instant Oatmeal Packets', 'snack', 'packaged_foods', 150, 5, 27, 3, ARRAY['fiber_rich']::text[], 4, 4, 5, true),
  ('fuel_packaged_057', 'Whole Grain Crackers', 'snack', 'packaged_foods', 130, 3, 22, 4, ARRAY['complex_carbs']::text[], 3, 5, 5, true),
  ('fuel_packaged_058', 'Peanut Butter Packets', 'snack', 'packaged_foods', 190, 7, 8, 16, ARRAY['healthy_fats']::text[], 3, 5, 5, true),
  ('fuel_packaged_059', 'Almond Butter Packets', 'snack', 'packaged_foods', 180, 6, 7, 16, ARRAY['healthy_fats']::text[], 4, 5, 5, true),
  ('fuel_packaged_060', 'Protein Shake (RTD)', 'drink', 'packaged_foods', 160, 30, 4, 2, ARRAY['high_protein']::text[], 5, 5, 5, true),
  ('fuel_packaged_061', 'Trail Mix (Low Sugar)', 'snack', 'packaged_foods', 200, 6, 18, 12, ARRAY['healthy_fats']::text[], 3, 5, 5, true),
  ('fuel_packaged_062', 'Rice Cakes', 'snack', 'packaged_foods', 35, 1, 7, 0, ARRAY['low_calorie']::text[], 4, 5, 5, true),
  ('fuel_packaged_063', 'Canned Chicken Breast', 'snack', 'packaged_foods', 120, 22, 0, 3, ARRAY['lean_protein']::text[], 5, 4, 5, true),
  ('fuel_packaged_064', 'Canned Black Beans', 'snack', 'packaged_foods', 110, 7, 20, 0, ARRAY['fiber_rich', 'vegetarian']::text[], 4, 3, 5, true),
  ('fuel_packaged_065', 'Canned Soup (Low Sodium)', 'meal', 'packaged_foods', 180, 12, 22, 5, ARRAY['comfort_food']::text[], 3, 4, 5, true),
  ('fuel_packaged_066', 'Microwave Brown Rice Cup', 'meal', 'packaged_foods', 210, 5, 44, 2, ARRAY['complex_carbs']::text[], 4, 3, 5, true),
  ('fuel_packaged_067', 'Shelf-Stable Chicken Salad Kit', 'meal', 'packaged_foods', 260, 12, 20, 14, ARRAY['portable']::text[], 3, 5, 5, true),
  ('fuel_packaged_068', 'Instant Mashed Potatoes Cup', 'meal', 'packaged_foods', 190, 4, 35, 4, ARRAY['comfort_food']::text[], 3, 4, 5, true),
  ('fuel_packaged_069', 'Whole Wheat Tortillas', 'snack', 'packaged_foods', 130, 4, 22, 3, ARRAY['complex_carbs']::text[], 4, 5, 5, true),
  ('fuel_packaged_070', 'Shelf-Stable Tofu', 'snack', 'packaged_foods', 90, 10, 2, 5, ARRAY['vegetarian', 'high_protein']::text[], 5, 3, 5, true),
  ('fuel_packaged_071', 'Canned Sardines', 'snack', 'packaged_foods', 180, 22, 0, 10, ARRAY['omega_3', 'high_protein']::text[], 5, 4, 5, true),
  ('fuel_packaged_072', 'Protein Cookies (Low Sugar)', 'snack', 'packaged_foods', 220, 16, 20, 8, ARRAY['high_protein']::text[], 3, 5, 5, true),
  ('fuel_packaged_073', 'Applesauce Cup (No Sugar Added)', 'snack', 'packaged_foods', 50, 0, 13, 0, ARRAY['low_calorie']::text[], 4, 5, 5, true),
  ('fuel_packaged_074', 'Dried Fruit (No Sugar Added)', 'snack', 'packaged_foods', 120, 1, 28, 0, ARRAY['natural_sugar']::text[], 3, 5, 5, true),
  ('fuel_packaged_075', 'Electrolyte Drink (Zero Sugar)', 'drink', 'packaged_foods', 5, 0, 1, 0, ARRAY['hydration']::text[], 5, 5, 5, true),
  ('fuel_packaged_076', 'Sparkling Water', 'drink', 'packaged_foods', 0, 0, 0, 0, ARRAY['hydration']::text[], 5, 5, 5, true),
  ('fuel_packaged_077', 'Whole Grain Cereal Cup', 'meal', 'packaged_foods', 150, 4, 32, 2, ARRAY['complex_carbs']::text[], 4, 4, 5, true),
  ('fuel_packaged_078', 'Shelf-Stable Milk Carton', 'drink', 'packaged_foods', 110, 8, 12, 4, ARRAY['protein_source']::text[], 4, 5, 5, true),
  ('fuel_packaged_136', 'Low-Sodium Turkey Jerky', 'snack', 'packaged_foods', 70, 11, 3, 1, ARRAY['lean_protein']::text[], 4, 5, 5, true),
  ('fuel_packaged_137', 'Protein Granola Cup', 'snack', 'packaged_foods', 210, 12, 28, 6, ARRAY['high_protein']::text[], 4, 5, 5, true),
  ('fuel_packaged_138', 'High-Protein Pudding Cup', 'snack', 'packaged_foods', 140, 15, 12, 4, ARRAY['high_protein']::text[], 4, 5, 5, true),
  ('fuel_packaged_139', 'Whole Grain Pretzel Thins', 'snack', 'packaged_foods', 110, 3, 23, 1, ARRAY['whole_grain']::text[], 3, 5, 5, true),
  ('fuel_mealprep_079', 'Chicken, Rice & Veggies Bowl', 'meal', 'meal_prep', 450, 40, 50, 10, ARRAY['balanced', 'high_protein']::text[], 5, 3, 5, true),
  ('fuel_mealprep_080', 'Overnight Oats', 'meal', 'meal_prep', 350, 20, 45, 8, ARRAY['fiber_rich']::text[], 4, 5, 5, true),
  ('fuel_mealprep_081', 'Turkey Wrap', 'meal', 'meal_prep', 320, 28, 30, 10, ARRAY['lean_protein']::text[], 4, 5, 5, true),
  ('fuel_mealprep_082', 'Chicken Salad (Greek Yogurt Base)', 'meal', 'meal_prep', 280, 32, 8, 12, ARRAY['high_protein']::text[], 5, 4, 5, true),
  ('fuel_mealprep_083', 'Tuna & Crackers Pack', 'snack', 'meal_prep', 260, 20, 22, 10, ARRAY['lean_protein']::text[], 4, 5, 5, true),
  ('fuel_mealprep_084', 'Beef & Veggie Stir Fry (12V Oven)', 'meal', 'meal_prep', 520, 42, 35, 22, ARRAY['high_protein']::text[], 4, 2, 5, true),
  ('fuel_mealprep_085', 'Egg Muffin Cups', 'snack', 'meal_prep', 180, 16, 4, 10, ARRAY['high_protein', 'low_carb']::text[], 5, 4, 5, true),
  ('fuel_mealprep_086', 'Cold Pasta Salad (Chicken)', 'meal', 'meal_prep', 480, 32, 55, 12, ARRAY['balanced']::text[], 4, 4, 5, true),
  ('fuel_mealprep_087', 'Veggie & Hummus Box', 'snack', 'meal_prep', 300, 10, 32, 14, ARRAY['vegetarian']::text[], 4, 5, 5, true),
  ('fuel_mealprep_088', 'Chicken Quesadilla (12V Oven)', 'meal', 'meal_prep', 420, 32, 30, 18, ARRAY['balanced']::text[], 3, 3, 5, true),
  ('fuel_mealprep_089', 'Protein Pancakes (Pre-Made)', 'meal', 'meal_prep', 320, 28, 38, 6, ARRAY['high_protein']::text[], 4, 5, 5, true),
  ('fuel_mealprep_090', 'Chicken Caesar Wrap (Homemade)', 'meal', 'meal_prep', 430, 36, 32, 18, ARRAY['balanced']::text[], 3, 4, 5, true),
  ('fuel_mealprep_091', 'Cold Cut Protein Box', 'meal', 'meal_prep', 380, 32, 10, 22, ARRAY['low_carb']::text[], 4, 5, 5, true),
  ('fuel_mealprep_092', 'Rice & Beans Bowl', 'meal', 'meal_prep', 420, 18, 70, 6, ARRAY['vegetarian', 'fiber_rich']::text[], 4, 4, 5, true),
  ('fuel_mealprep_093', 'Chicken Burrito Bowl', 'meal', 'meal_prep', 520, 42, 55, 14, ARRAY['high_protein']::text[], 4, 3, 5, true),
  ('fuel_mealprep_094', 'Turkey Chili (12V Oven)', 'meal', 'meal_prep', 380, 32, 40, 10, ARRAY['high_protein', 'fiber_rich']::text[], 5, 2, 5, true),
  ('fuel_mealprep_095', 'Cold Chicken Pasta', 'meal', 'meal_prep', 460, 34, 55, 12, ARRAY['balanced']::text[], 4, 4, 5, true),
  ('fuel_mealprep_096', 'Egg Salad Wrap', 'meal', 'meal_prep', 380, 22, 28, 18, ARRAY['balanced']::text[], 3, 4, 5, true),
  ('fuel_mealprep_097', 'Cold Steak Strips & Veggies', 'meal', 'meal_prep', 420, 40, 12, 22, ARRAY['low_carb', 'high_protein']::text[], 5, 4, 5, true),
  ('fuel_mealprep_098', 'Chicken & Sweet Potato Meal', 'meal', 'meal_prep', 480, 38, 55, 10, ARRAY['balanced']::text[], 5, 3, 5, true),
  ('fuel_mealprep_099', 'Greek Chicken Pita', 'meal', 'meal_prep', 420, 36, 40, 12, ARRAY['balanced']::text[], 4, 4, 5, true),
  ('fuel_mealprep_100', 'Cold Peanut Noodle Bowl', 'meal', 'meal_prep', 520, 20, 60, 20, ARRAY['vegetarian']::text[], 3, 4, 5, true),
  ('fuel_mealprep_101', 'Chicken & Quinoa Bowl', 'meal', 'meal_prep', 480, 38, 55, 12, ARRAY['high_protein', 'balanced']::text[], 5, 3, 5, true),
  ('fuel_mealprep_140', 'Chicken & Brown Rice Meal', 'meal', 'meal_prep', 480, 42, 52, 12, ARRAY['balanced', 'high_protein']::text[], 5, 3, 5, true),
  ('fuel_gasstation_102', 'String Cheese', 'snack', 'gas_station_options', 80, 7, 1, 6, ARRAY['portable', 'high_protein']::text[], 4, 5, 5, true),
  ('fuel_gasstation_103', 'Fresh Fruit Cup', 'snack', 'gas_station_options', 90, 1, 22, 0, ARRAY['low_calorie', 'hydrating']::text[], 5, 5, 5, true),
  ('fuel_gasstation_104', 'Banana', 'snack', 'gas_station_options', 105, 1, 27, 0, ARRAY['natural_sugar']::text[], 4, 5, 5, true),
  ('fuel_gasstation_105', 'Apple', 'snack', 'gas_station_options', 95, 0, 25, 0, ARRAY['fiber_rich']::text[], 5, 5, 5, true),
  ('fuel_gasstation_106', 'Beef Jerky (Low Sodium)', 'snack', 'gas_station_options', 80, 12, 3, 2, ARRAY['high_protein']::text[], 4, 5, 5, true),
  ('fuel_gasstation_107', 'Protein Shake (RTD)', 'drink', 'gas_station_options', 160, 30, 4, 2, ARRAY['high_protein']::text[], 5, 5, 5, true),
  ('fuel_gasstation_108', 'Hard-Boiled Eggs (2-pack)', 'snack', 'gas_station_options', 140, 12, 2, 9, ARRAY['high_protein']::text[], 4, 5, 5, true),
  ('fuel_gasstation_109', 'Veggie Snack Tray', 'snack', 'gas_station_options', 70, 2, 14, 0, ARRAY['low_calorie']::text[], 5, 5, 5, true),
  ('fuel_gasstation_110', 'Hummus Cup', 'snack', 'gas_station_options', 160, 5, 14, 10, ARRAY['vegetarian']::text[], 4, 4, 5, true),
  ('fuel_gasstation_111', 'Trail Mix (Low Sugar)', 'snack', 'gas_station_options', 200, 6, 18, 12, ARRAY['healthy_fats']::text[], 3, 5, 5, true),
  ('fuel_gasstation_112', 'Mixed Nuts', 'snack', 'gas_station_options', 170, 6, 6, 15, ARRAY['healthy_fats']::text[], 3, 5, 5, true),
  ('fuel_gasstation_113', 'Granola Bar (Low Sugar)', 'snack', 'gas_station_options', 140, 4, 22, 4, ARRAY['portable']::text[], 3, 5, 5, true),
  ('fuel_gasstation_114', 'Electrolyte Drink (Zero Sugar)', 'drink', 'gas_station_options', 5, 0, 1, 0, ARRAY['hydration']::text[], 5, 5, 5, true),
  ('fuel_gasstation_115', 'Sparkling Water', 'drink', 'gas_station_options', 0, 0, 0, 0, ARRAY['hydration']::text[], 5, 5, 5, true),
  ('fuel_gasstation_116', 'Applesauce Cup (No Sugar Added)', 'snack', 'gas_station_options', 50, 0, 13, 0, ARRAY['low_calorie']::text[], 4, 5, 5, true),
  ('fuel_gasstation_117', 'Pretzel Pack', 'snack', 'gas_station_options', 110, 2, 23, 1, ARRAY['quick_carbs']::text[], 3, 5, 5, true),
  ('fuel_gasstation_118', 'Popcorn (Light)', 'snack', 'gas_station_options', 100, 3, 18, 2, ARRAY['low_calorie']::text[], 4, 5, 5, true),
  ('fuel_gasstation_119', 'Protein Cookie (Low Sugar)', 'snack', 'gas_station_options', 220, 16, 20, 8, ARRAY['high_protein']::text[], 3, 5, 5, true)
on conflict (id) do update set
  name = excluded.name,
  type = excluded.type,
  category = excluded.category,
  calories = excluded.calories,
  protein = excluded.protein,
  carbs = excluded.carbs,
  fat = excluded.fat,
  tags = excluded.tags,
  health_score = excluded.health_score,
  convenience_score = excluded.convenience_score,
  truck_access_score = excluded.truck_access_score,
  is_active = excluded.is_active;

